Fix NULL fields being added to the fields array
> Warning: Creating default object from empty value in
/[..]/gravityview/includes/extensions/edit-entry/class-edit-entry-render
.php on line 1821
>
> Warning: Creating default object from empty value in
/[..]/gravityview/includes/extensions/edit-entry/class-edit-entry-render
.php on line 1821
>
> Fatal error: Cannot use object of type stdClass as array in
/[..]/gravityforms/forms_model.php on line 2815

Note to self: If you check for whether $i exists, and it doesn't, and
then you add the field using the `GVCommon::get_field()` method, it
results in duplicate fields being added. Just setting if exists is
enough to get it right.